package documentation.resources.coverlayResources

val labels = listOf(
    "cellsScale",
    "cellsX",
    "cellsY",
    "decay",
    "fd",
    "fxAmount",
    "gain",
    "poisson",
    "radius",
    "scale",
    "velocity",
    "centerHue",
    "contrastReversal",
    "dimensions",
    "yAngle",
    "angle",
    "attractorPosX",
    "attractorPosY",
    "complexity",
    "concentricity",
    "randomAngle",
    "rotMovement",
    "height",
    "heightSegments",
    "noise",
    "noiseFrequency",
    "noiseScale",
    "rotationSegments",
    "width",
    "cNoise",
    "cNoiseFreq",
    "cOffset",
    "visibility",
    "waveAmount",
    "waveFrequency",
    "wavePhase",
    "waveform",
    "cellType",
    "corners",
    "v_penPressure",
    "v_thickness",
    "v_turbulenceAmount",
    "v_turbulenceScale",
    "h_penPressure",
    "h_thickness",
    "h_turbulenceAmount",
    "h_turbulenceScale"
)

fun main() {
    println(labels.size)
}